apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-spring-petclinic
spec:
  workspaces:
    - name: shared-workspace
      description: Workspace shared by all tasks
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
    - name: image
      type: string
    - name: skip-tests
      type: string
      default: "false"
    - name: fail-on-severity
      type: string
      default: "NONE"
    - name: extra-files-configmap
      type: string
      default: "spring-petclinic-extra-files"
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone-petclinic
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: extra-files-configmap
          value: $(params.extra-files-configmap)
    - name: run-unit-tests
      taskRef:
        name: maven-test-petclinic
      when:
        - input: "$(params.skip-tests)"
          operator: in
          values: ["false"]
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build-image
      taskRef:
        name: buildah-spring-petclinic
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: image
          value: $(params.image)
    - name: scan-image
      taskRef:
        name: trivy-scan-petclinic
      runAfter:
        - build-image
      params:
        - name: image
          value: $(params.image)
        - name: fail-on-severity
          value: $(params.fail-on-severity)
