apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-petclinic
spec:
  workspaces:
    - name: output
      description: The git repo will be cloned onto the volume backing this workspace
  params:
    - name: url
      description: git url to clone
      type: string
    - name: revision
      description: git revision to checkout (branch, tag, sha, ref…)
      type: string
      default: main
    - name: extra-files-configmap
      description: Optional configmap name containing extra files to copy into workspace
      type: string
      default: "none"
  steps:
    - name: clone
      image: alpine/git:latest
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh
        set -e
        echo "Clearing workspace..."
        rm -rf *
        rm -rf .git
        echo "Cloning $(params.url) @ $(params.revision)..."
        git clone --branch "$(params.revision)" "$(params.url)" .
        
        # If the configmap mount exists, copy its contents to the workspace
        if [ -d /mnt/extra-files ]; then
          echo "Copying extra files from ConfigMap..."
          cp -RL /mnt/extra-files/* .
        fi
        
        echo "Setting ownership to user 1000 to allow modification by subsequent tasks..."
        chown -R 1000:1000 .
        echo "Done!"
        ls -la
      volumeMounts:
        - name: extra-files
          mountPath: /mnt/extra-files
  volumes:
    - name: extra-files
      configMap:
        name: $(params.extra-files-configmap)
        optional: true
