apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
        - name: petclinic
          image: REGISTRY_IMAGE_URL
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
  namespace: default
spec:
  selector:
    app: spring-petclinic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
